export const HINT_SEARCH = 'Buscar...';
export const SEARCH_DATA = 'searchData';
export const PLAYBACK = 'Playback';
export const PLAY = 'Play';
export const VOLUME = 1;
export const DARK = 'dark';
export const SONG_ERROR = 'Canción no disponible';
export const JUMP_INTERVAL = 10;
export const SONG_INFO_SCREEN = 'Song Info';
